# Full working
name: GeoPython38env
channels:
  - conda-forge
#  - numba
#  - rapidsai
#  - mro
#  - r
#  #  - conda-forge/label/broken
#  - defaults
dependencies:
  - coverage
  - docopt
  - fiona
  - gdal
  - matplotlib-base
  - matplotlib
  - numpy
  - pandas
  - python==3.8
  - pip
  - pyproj
  - scikit-image
  - geopandas
  - descartes
  - pysal
  - affine
  - rasterstats>=0.12
  - statsmodels
  - seaborn
  - geoplot
  - cython
  - datashader
  - datashape
  - georasters
  - pandas-datareader
  - pandana
  - pycountry
  - urbanaccess
  - r
  - r-base
  #- rstudio
  - r-irkernel
  - sympy
  - rpy2
  - r-tidyr
  - r-tibble
  - r-dplyr
  - scikit-learn
  - scipy
  - unidecode
  - urllib3
  - wikipedia
  - xlrd
  - jupyter_contrib_nbextensions
  - geopy
  - geographiclib
#  - geotiff
#  - imageio
#  - imagesize
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyterlab
  - kiwisolver
  - markdown
  - networkx
  - nose
  - numba
  - numpy
  - openpyxl
#  - pandasql
#  - rstudio
  - r-irkernel
  - sympy
  - rpy2
  - rasterio
  - r-tidyr
  - r-tibble
  - r-dplyr
  - rise
  - scikit-allel
  - scikit-bio
  - scikit-image
  - scikit-learn
  - scipy
  - swifter
  - unidecode
  - urllib3
  - wikipedia
  - xlrd
  - asciitree
  - autopep8
  - babel
  - basemap
  - beautifulsoup4
  - blas
#  - blaze
  - bokeh
  - bzip2
  - cartopy
  - colorcet
  - curl
  - cytoolz
  - dask
  - dask-core
  - dill
  - docutils
  - earthengine-api
  - gensim
  - geotiff
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - imageio
  - imagesize
  - pandoc
  - pandocfilters
  - pelican
  - pymc3
  - theano
  - camelot-py
  - html5lib
  - ghostscript
  - pip:
    - linearmodels
    - git+https://github.com/jeetsukumaran/DendroPy.git
    - git+https://github.com/dmsul/econtools
    - ecopy
    - facebook-business
    - facebook-sdk
    - fontawesome-markdown
    - geocoder
    - geonamescache
    - googledrivedownloader
    - googletrans
    - ipystata
    - isodate
    - isounidecode
    - latexcodec
    - ldpred
    - linearmodels
    - lingpy
    - mccabe
    - ordered-set
    - plinkio
    - pyarrow
    - pybtex
    - pycldf
    - pycountry
    - pydocstyle
    - pyface
    - pyflakes
    - pylatex
    - pyparsing
    - pyreadstat
    - pytest-cov
    - python-jsonrpc-server
    - python-language-server
    - pytrends
    - quilt
    - ratelim
    - readme-renderer
    - rfc3986
    - rope
    - simpledbf
    - simplejson
    - smartypants
    - snowballstemmer
    - snuggs
    - stata-kernel
    - tabulate
    - tex2ipy
    - texsoup
    - toolz
    - traits
    - traitsui
    - twine
    - typogrify
    - uritemplate
    - w3lib
    - webencodings
    - wrapt
    - xlwt
    - yapf
    - modin
    - stargazer
    - covid
    - COVID19Py
